echo "Hola desde Jenkins 🚀"
echo "El job está funcionando correctamente ✅"
echo "¡Gracias por usar Jenkins! 🎉"
echo "Probando trigger desde github y jenkins... 🔄"
echo "Prueba desde webhook 🚀(github notifica a jenkins)"